version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: backend-image
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  frontend:
    build: ./frontend
    image: frontend-image
    container_name: frontend-container
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
